spring:
  application:
    name: CloudBalance
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  logging:
    level:org.springframework.security: DEBUG
#  datasource:
#    username: root
#    password: Root@123
#    url: jdbc:mysql://localhost:3306/cloudbalance
#    driver-class-name: com.mysql.cj.jdbc.Driver